# [build]
# Uncomment to build binary with custom target:
# target = "x86_64-aethelos.json"

[target.x86_64-aethelos]
# Use LLD as the linker with our linker script
rustflags = [
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=--no-pie",
    "-C", "link-arg=-static",
    "-C", "link-arg=--no-dynamic-linker",
    "-C", "link-arg=-n",  # --nmagic: Don't page-align file offsets
    "-C", "link-arg=-z",
    "-C", "link-arg=max-page-size=0x1000",
    "-C", "link-arg=-TF:/OS/heartwood/linker.ld",
    "-C", "relocation-model=static",
]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
